% Version 2010b. General program improvements by J C Cremon, in
% collaboration with Sara Bargi.


% 2010-04-15:
% Moved all 'units','normal' parameters to be placed before the 'pos'
% parameters, since this otherwise causes warnings on late Matlab versions.
% by J C Cremon

% Original version from 990906, utvecklad av Fredrik Frisk och Per Östborn.





menyfigur = figure('MenuBar','none','color',[0.6 0.6 0.6],'name','Indata Schrödingerekvationen', ...
                 'numbertitle','off','papertype','a4','position',[150 100 720 600]);

%
%
%       initiering av variabler
%
L = 0;
Z = 1;
Energy_old = -2;
L_old = 1;
Z_old = 3;
egen_H0 = [];
egen_Li0 = [];
egen_H1 = [];
egen_Li1 = [];
egen_H2 = [];
egen_Li2 = [];
egen_H3 = [];
egen_Li3 = [];
egen_H4 = [];
egen_Li4 = [];
r = 0.0025:0.0025:30;
wave_function =zeros(size(r));
r1 = 0.05:0.05:30;
wave_function1 = zeros(size(r1));
%
wave_plot=axes('pos',[0.1 0.47 0.8 0.45]);
gca = wave_plot;
line([0 30],[0 0],'linestyle','--')
set(gca,'YLim',[-0.2 0.2]);
set(gca,'xlim',[0 30]);
set(gca,'ytick',[]);
xlabel('Ångström');

txt_version = uicontrol(menyfigur,'style','text','string', ...
   'Version 2010b. (Ursprungligen 1999 av Fredrik Frisk och Per Östborn.)', ... 
    'units','normal','pos',[0.1 0.95 0.8 0.025]);

kontroll_frame=uicontrol(menyfigur,'style','frame','units','normal','pos',[0.1 0.14 0.8 0.25]);

%
radio_frame = uicontrol(menyfigur,'style','frame','units','normal','pos',[0.13 0.26 0.25 .08]);
txt_grund = uicontrol(menyfigur,'style','text','string','Välj grundämne', ...
		'units','normal','pos',[0.12 0.35 0.2 0.025]);

%
%     Val av grundämne!!!
%
radio_h = uicontrol(menyfigur,'style','radio','string','Hydrogen potential', ...
			'units','normal','pos',[0.14 0.3 0.23 0.03],'val',1, ...
			'callback',[ ...
				'set(radio_h,''val'',1),' ...
				'set(radio_li,''val'',0),' ...
				'Z = 1;,']);
radio_li = uicontrol(menyfigur,'style','radio','string','User-defined potential', ...
			'units','normal','pos',[0.14 0.27 0.23 0.03],'val',0, ...
			'callback',[ ...
				'set(radio_h,''val'',0),' ...
				'set(radio_li,''val'',1),' ...
				'Z = 3;,']);
%
%
%
L_frame = uicontrol(menyfigur,'style','frame', ...
   'units','normal','pos',[0.45 0.17 0.1 0.17]);
txt_grund = uicontrol(menyfigur,'style','text','string','Ställ in L-kvanttalet', ...
		'units','normal','pos',[0.4 0.35 0.2 0.025]);
%
%
% 		Inställning av L kvanttal
%

% 2010-04-15: Option for L = 4 removed. / J C Cremon


L_0 = uicontrol(menyfigur,'style','radio','string','L=0', ...
			'units','normal','pos',[0.47 0.18 0.07 0.03],'val',1, ...
			'callback',[ ...
				'set(L_0,''val'',1),' ...
				'set(L_1,''val'',0),' ...
				'set(L_2,''val'',0),' ...
				'set(L_3,''val'',0),' ...
				'L = 0;,']);
%
L_1 = uicontrol(menyfigur,'style','radio','string','L=1', ...
			'units','normal','pos',[0.47 0.21 0.07 0.03],'val',0, ...
			'callback',[ ...
				'set(L_0,''val'',0),' ...
				'set(L_1,''val'',1),' ...
				'set(L_2,''val'',0),' ...
				'set(L_3,''val'',0),' ...
				'L = 1;,']);
%
L_2 = uicontrol(menyfigur,'style','radio','string','L=2', ...
			'units','normal','pos',[0.47 0.24 0.07 0.03],'val',0, ...
			'callback',[ ...
				'set(L_0,''val'',0),' ...
				'set(L_1,''val'',0),' ...
				'set(L_2,''val'',1),' ...
				'set(L_3,''val'',0),' ...
				'L = 2;,']);
%
L_3 = uicontrol(menyfigur,'style','radio','string','L=3', ...
			'units','normal','pos',[0.47 0.27 0.07 0.03],'val',0, ...
			'callback',[ ...
				'set(L_0,''val'',0),' ...
				'set(L_1,''val'',0),' ...
				'set(L_2,''val'',0),' ...
				'set(L_3,''val'',1),' ...
				'L = 3;,']);

txt_egen = uicontrol(menyfigur,'style','text','string', ...
		'Ställ in energin','units','normal','pos',[0.66 0.35 0.2 0.025]);
   
energiruta=uicontrol(menyfigur,'style','edit','string','-13.6', ...
   'units','normal','pos',[0.69 0.3 0.14 0.03], ...
   'callback','E=str2num(get(energiruta,''string''));kolla_E;','backgroundcolor',[1 1 1]);

energienhet=uicontrol(menyfigur,'style','text','string', ...
      'eV','units','normal','pos',[0.84 0.3 0.04 0.025]);
   
meddelande=uicontrol(menyfigur,'style','text','units','normal','pos',[0.69 0.25 0.15 0.025], ...
         'string','improper input !', ...
         'visible','off');
   
pb_start = uicontrol(menyfigur,'style','push','units','normal','pos',[0.15 0.05 0.35 0.05],'enable','on', ...
       		'string','Testa vågfunktion för given energi','callback','EnivHLi'); 

% Button for auto-script added by J C Cremon, 2010-04-15:
pb_start = uicontrol(menyfigur,'style','push','units','normal','pos',[0.55 0.05 0.35 0.05],'enable','on','string','Auto-sök från given energi','callback','auto'); 
        
E=str2num(get(energiruta,'string'));
kolla_E;
